import dotenv from 'dotenv';
import {
  ALONE,
  Alone,
  Device,
  DEVICE,
  LOCATION,
  Location,
  setupDb,
  testDevices,
  testLocations,
  testSchema,
} from '../test/test-utils';
import { CrudRepository } from './crud.repository';
import { DSL } from './dsl/dsl';
import { DSLContext } from './dsl/dsl.context';

dotenv.config();

describe('withDatabase', () => {
  setupDb(beforeEach, testSchema);
  let create: DSLContext;
  let locationRepository: CrudRepository<Location, 'id'>;
  let deviceRepository: CrudRepository<Device, 'mac'>;
  beforeEach(async () => {
    create = DSL.context({
      type: 'postgres',
      config: {
        connectionString: process.env.DATABASE_URL,
      },
    });
    locationRepository = new CrudRepository(create, LOCATION, 'id');
    deviceRepository = new CrudRepository(create, DEVICE, 'mac');
  });
  afterEach(async () => {
    await create.end();
  });
  it('crud', async () => {
    const locations = await locationRepository.insertAll(testLocations);
    locations.sort((a, b) => a.id - b.id);
    expect(locations).toStrictEqual(testLocations);
    const loadedLoactions = await locationRepository.findAll();
    loadedLoactions.sort((a, b) => a.id - b.id);
    expect(loadedLoactions).toStrictEqual(testLocations);
    let l = await locationRepository.findOneByIdOrThrow(testLocations[0].id);
    expect(l).toStrictEqual(testLocations[0]);
    l = await locationRepository.findOneByIdOrThrow(testLocations[0].id);
    expect(l).toStrictEqual(testLocations[0]);
    await expect(locationRepository.findOneByIdOrThrow(1234)).rejects.toThrow();
    expect(await locationRepository.findOneById(12345)).toBeUndefined;
    const found = await locationRepository.find(
      LOCATION.name.eq(testLocations[1].name),
    );
    expect(found.length).toBe(1);
    expect(found[0]).toStrictEqual(testLocations[1]);
    l = await locationRepository.findFirst(
      LOCATION.name.eq(testLocations[1].name),
    );
    expect(l).toStrictEqual(testLocations[1]);
    expect(
      await locationRepository
        .selectId()
        .where(LOCATION.name.eq(testLocations[2].name))
        .fetchOneOrThrow(),
    ).toBe(testLocations[2].id);
    await locationRepository.deleteById(testLocations[0].id);
    expect((await locationRepository.findAll()).length).toBe(
      testLocations.length - 1,
    );
    await locationRepository.delete(LOCATION.id.eq(testLocations[1].id));
    expect((await locationRepository.findAll()).length).toBe(
      testLocations.length - 2,
    );
  });
  it('insertAutoGenerated single', async () => {
    const testData: Alone[] = [
      { id: 100, name: 'a', bool: true, date: new Date() },
      {
        id: 101,
        name: 'b',
        bool: false,
        date: new Date(),
        roflKopter: 'asdf',
      } as Alone,
      { id: 102, name: 'c', date: new Date() },
    ];
    const aloneRepository = new CrudRepository(create, ALONE, 'id');
    let test = await aloneRepository.insertAutoGenerated(testData[0]);
    expect(test).toBeTruthy();
    expect(test.id).toBe(1);
    test = await aloneRepository.insertAutoGenerated(testData[1]);
    expect(test).toBeTruthy();
    expect(test.id).toBe(2);
  });
  it('insertAutoGenerated all', async () => {
    const testData: Alone[] = [
      { id: 100, name: 'a', bool: true, date: new Date() },
      {
        id: 101,
        name: 'b',
        bool: false,
        date: new Date(),
        roflKopter: 'asdf',
      } as Alone,
      { id: 102, name: 'c', date: new Date() },
    ];
    const aloneRepository = new CrudRepository(create, ALONE, 'id');
    const list = await aloneRepository.insertAllAutoGenerated(testData);
    expect(list.length).toBe(testData.length);
    for (const alone of list) {
      expect(alone.id).not.toBeUndefined();
      expect(alone.id).toBeLessThan(100);
    }
  });

  it('fetchOneToMany', async () => {
    await locationRepository.insertAll(testLocations);
    await deviceRepository.insertAll(testDevices);
    const locationsDevices = await await deviceRepository.fetchOneToMany(
      [1, 2, 3],
      'idLocation',
      DEVICE.idLocation,
      [],
    );
    expect(locationsDevices.length).toBe(3);
    expect(locationsDevices[0].length).toBe(3);
    expect(locationsDevices[1].length).toBe(4);
    expect(locationsDevices[2].length).toBe(0);
  });
  it('mapOneToMany', async () => {
    await locationRepository.insertAll(testLocations);
    await deviceRepository.insertAll(testDevices);
    const locations = await locationRepository.findAll();
    const locationsWithDevices = await locationRepository.mapOneToMany(
      locations,
      'a',
      deviceRepository,
      'idLocation',
      DEVICE.idLocation,
    );
    locationsWithDevices.sort((a, b) => a.id - b.id);
    expect(locationsWithDevices.length).toBe(3);
    expect(locationsWithDevices[0].a.length).toBe(3);
    expect(locationsWithDevices[1].a.length).toBe(4);
    expect(locationsWithDevices[2].a.length).toBe(0);
  });
  it('fetchOneToOne', async () => {
    await locationRepository.insertAll(testLocations);
    await deviceRepository.insertAll(testDevices);
    const locationsDevices = await await deviceRepository.fetchOneToOne(
      [1, 2, 3],
      'idLocation',
      DEVICE.idLocation,
      [],
    );
    expect(locationsDevices.length).toBe(3);
    expect(locationsDevices[0]).toBeTruthy();
    expect(locationsDevices[1]).toBeTruthy();
    expect(locationsDevices[2]).toBeFalsy();

    expect(locationsDevices[0]?.idLocation).toBe(1);
    expect(locationsDevices[1]?.idLocation).toBe(2);
  });
  it('insertOrUpdate', async () => {
    const aloneRepository = new CrudRepository(create, ALONE, 'id');
    const test = await aloneRepository.insertOrUpdate({
      name: 'test',
    });
    expect(test).toBeTruthy();
    expect(test.bool).toBeUndefined();
    test.bool = true;
    const test2 = await aloneRepository.insertOrUpdate(test);
    expect(test2).toBeTruthy();
    expect(test2.bool).toBe(true);
  });
  it('deleteAll', async () => {
    const aloneRepository = new CrudRepository(create, ALONE, 'id');
    await aloneRepository.insertAllAutoGenerated([
      { id: 100, name: 'a', bool: true, date: new Date() },
      {
        id: 101,
        name: 'b',
        bool: false,
        date: new Date(),
        roflKopter: 'asdf',
      } as Alone,
      { id: 102, name: 'c', date: new Date() },
    ]);
    const data = await aloneRepository.findAll();
    expect(data.length).toBe(3);
    await aloneRepository.deleteAll();
    const dataEmpty = await aloneRepository.findAll();
    expect(dataEmpty.length).toBe(0);
  });

  it('insertOnConflictDoNothing', async () => {
    const aloneRepository = new CrudRepository(create, ALONE, 'id');
    const d: Alone = {
      id: 101,
      name: 'b',
      bool: false,
      date: new Date(),
    };
    expect(await aloneRepository.insertOnConflictDoNothing(d)).toBeTruthy();
    expect(await aloneRepository.insertOnConflictDoNothing(d)).toBe(undefined);
  });
});
