version: '3.8'
services:
  postgres:
    image: postgres:12
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: development
      POSTGRES_DB: tsooq
    volumes:
      - ./conf/dbSetup:/docker-entrypoint-initdb.d
    ports:
    - 5432:5432
